name: "Alesil RabbitMQ"
slug: "alesil-rabbitmq"
description: "Servidor RabbitMQ como Add-On do Home Assistant"
version: "v1.0.7" #não esquecer de atualizar a versão no arquivo .github/workflows/docker-build-rabbitmq-arm64.yaml também (e dar commit) para que o Home Assistant atualize o addon automaticamente (se estiver instalado)
url: "https://github.com/aledevbr/homelend-homeassistant-poc"
arch:
  # - armhf
  # - armv7
  - aarch64
  # - amd64
  # - i386
map:
  - share:rw
  - media:rw
  - homeassistant_config:rw
  - addon_config:rw
  - ssl:rw
  - backup:rw
  - addons:rw
  - all_addon_configs:rw
  
hassio_api: false
hassio_role: default
homeassistant_api: false
docker_api: false

panel_icon: mdi:home-assistant
panel_admin: true
panel_title: "RabbitMQ"

#host_network: true
host_network: false
ingress: true
ingress_port: 15672
ingress_entry: "/"

ports:
  5672/tcp: 5672
  15672/tcp: 15672

init: false
startup: application
boot: auto
image: "ghcr.io/aledevbr/homelend-homeassistant-poc-rabbitmq"
#webui: "http://[HOST]:[PORT:8080]"
