---
version: 1.0.0
slug: "homelend-blazor-poc"
name: "Homelend Blazor POC"
description: "AddOn web Blazor para teste no Home Assistant"
url: "https://github.com/aledevbr/homelend-homeassistant-poc"
arch:
  - aarch64
hassio_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:home-assistant
panel_title: "Homelend Blazor POC"
ports:
  8080/tcp: 8080
  8081/tcp: 8081
init: false
startup: services
image: ghcr.io/aledevbr/homelend-homeassistant-poc:latest
webui: "http://[HOST]:[PORT:8080]"

# {
#   "name": "Homelend Blazor POC",
#   "version": "1.0",
#   "slug": "homelend-blazor-poc",
#   "description": "AddOn web Blazor para teste no Home Assistant",
#   "arch": [ "aarch64" ],
#   "startup": "application",
#   "boot": "auto",
#   "host_network": false,
#   "ports": {
#     "8080/tcp": 8080,
#     "8081/tcp": 8081
#   },
#   "ports_description": {
#     "8080/tcp": "Blazor Web Server",
#     "8081/tcp": "Blazor Web Server (SSL)"
#   },
#   "panel_icon": "mdi:home-assistant",
#   "panel_title": "Homelend Blazor POC",
#   "hassio_api": true,
#   "webui": "http://[HOST]:[PORT:8080]",
#   "homeassistant_api": true,
#   "ingress": true,
#   "ingress_port": 8080,
#   "ingress_entry": "/"
# }
