name: "Homelend Blazor POC"
slug: "homelend-blazor-poc"
description: "AddOn web Blazor para teste no Home Assistant"
version: "1.0.1"
url: "https://github.com/aledevbr/homelend-homeassistant-poc"
arch:
  # - armhf
  # - armv7
  - aarch64
  # - amd64
  # - i386
map:
  - share:rw
  # - media:rw
  # - homeassistant_config:rw
  # - addon_config:rw
  # - ssl:rw
  # - backup:rw
  # - addons:rw
  # - all_addon_configs:rw
  
# hassio_api: true
# hassio_role: admin
# homeassistant_api: true
# docker_api: true

host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:home-assistant
panel_admin: true
panel_title: "Homelend Blazor POC"
ports:
  8080/tcp: 8080
  8081/tcp: 8081
init: false
startup: application
boot: auto
image: "ghcr.io/aledevbr/homelend-homeassistant-poc:latest"
webui: "http://[HOST]:[PORT:8080]"

# {
#   "name": "Homelend Blazor POC",
#   "version": "1.0",
#   "slug": "homelend-blazor-poc",
#   "description": "AddOn web Blazor para teste no Home Assistant",
#   "arch": [ "aarch64" ],
#   "startup": "application",
#   "boot": "auto",
#   "host_network": false,
#   "ports": {
#     "8080/tcp": 8080,
#     "8081/tcp": 8081
#   },
#   "ports_description": {
#     "8080/tcp": "Blazor Web Server",
#     "8081/tcp": "Blazor Web Server (SSL)"
#   },
#   "panel_icon": "mdi:home-assistant",
#   "panel_title": "Homelend Blazor POC",
#   "hassio_api": true,
#   "webui": "http://[HOST]:[PORT:8080]",
#   "homeassistant_api": true,
#   "ingress": true,
#   "ingress_port": 8080,
#   "ingress_entry": "/"
# }
