name: "Homelend Blazor POC"
slug: "homelend-blazor-poc"
description: "AddOn web Blazor para teste no Home Assistant"
version: "v1.0.13" #não esquecer de atualizar a versão no arquivo .github/workflows/docker-build-dotnet-arm64.yaml também (e dar commit) para que o Home Assistant atualize o addon automaticamente (se estiver instalado)
url: "https://github.com/aledevbr/homelend-homeassistant-poc"
arch:
  # - armhf
  # - armv7
  - aarch64
  # - amd64
  # - i386
map:
  - share:rw
  # - media:rw
  # - homeassistant_config:rw
  # - addon_config:rw
  # - ssl:rw
  # - backup:rw
  # - addons:rw
  # - all_addon_configs:rw
  
hassio_api: true
hassio_role: admin
homeassistant_api: true
docker_api: true

panel_icon: mdi:home-assistant
panel_admin: true
panel_title: "Homelend Blazor POC"

#host_network: true
host_network: false
ingress: true
ingress_port: 8080
ingress_entry: ""

ports:
  8080/tcp: 8080
  # 8081/tcp: 8081
init: false
startup: application
boot: auto
image: "ghcr.io/aledevbr/homelend-homeassistant-poc"
#webui: "http://[HOST]:[PORT:8080]"
