name: Build and Publish Docker Image for ARM64

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      #uses: docker/setup-qemu-action@v1
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      #uses: docker/setup-buildx-action@v1
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      #uses: docker/login-action@v1
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker Buildx
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        #images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Build and Push Docker Image
      #uses: docker/build-push-action@v2
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./HomeAssistantPoc/HomeAssistantPoc/Dockerfile
        push: true
        #tags: ghcr.io/${{ github.repository }}/blazor-on-homeassistant:latest
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/arm64
